extends Node
signal player_state_changed(new_state, old_state)
signal player_crouched(is_crouched)
signal player_moved(direction, delta)
signal player_health_changed(health, max_health)
signal player_inventory_item_added(item)
signal player_inventory_item_removed(item)
signal player_stamina_changed(stamina)
signal player_speed_changed(speed)
signal player_gun_equipped(is_equipped)
signal player_gun_fired(position, direction)
signal player_cook_started
signal player_cook_completed
signal player_ability_activated(ability_name)
signal player_died
signal player_respawned
signal player_interacted_with_object(object)
signal player_touched_object(object)
signal player_collected_item(item)
signal player_entered_area(area_name)
signal player_exited_area(area_name)
signal player_entered_car
signal player_exited_car
signal player_entered_meth_lab
signal player_money_changed(amount)
signal npc_died(npc)
signal npc_detected_player(npc)
signal npc_lost_player(npc)
signal npc_state_changed(npc, state)
signal npc_dialog_started(npc)
signal npc_dialog_ended(npc)
signal npc_interacted(npc)
signal enemy_died(enemy)
signal enemy_spawned(enemy)
signal enemy_detected_player(enemy)
signal enemy_lost_player(enemy)
signal enemy_damaged(enemy, damage)
signal enemy_attacked(enemy)
signal game_state_changed(state)
signal game_paused(is_paused)
signal game_over(reason)
signal game_won
signal game_started
signal game_saved
signal game_loaded
signal game_difficulty_changed(difficulty)
signal game_day_changed(day)
signal game_time_changed(time_of_day)
signal game_weather_changed(weather)
signal game_heat_level_changed(heat_level)
signal game_police_alerted(reason)
signal game_money_earned(amount, source)
signal game_money_spent(amount, target)
signal game_quest_started(quest)
signal game_quest_updated(quest, progress)
signal game_quest_completed(quest)
signal game_achievement_unlocked(achievement)
signal game_tutorial_started(tutorial)
signal game_tutorial_completed(tutorial)
signal scene_transitioning(from_scene, to_scene)
signal scene_transitioned(to_scene)
signal ui_button_pressed(button_name)
signal ui_dialog_option_selected(option)
signal ui_menu_opened(menu_name)
signal ui_menu_closed(menu_name)
signal ui_notification_shown(message)
signal ui_tooltip_shown(text)
signal ui_tooltip_hidden
signal ui_inventory_opened
signal ui_inventory_closed
signal ui_inventory_item_selected(item)
signal ui_inventory_item_used(item)
signal ui_inventory_item_dropped(item)
signal ui_map_opened
signal ui_map_closed
signal ui_map_location_selected(location)
signal ui_phone_opened
signal ui_phone_closed
signal ui_phone_app_opened(app)
signal ui_phone_app_closed(app)
signal ui_phone_call_received(caller)
signal ui_phone_call_answered(caller)
signal ui_phone_call_declined(caller)
signal ui_phone_call_ended(caller)
signal ui_phone_message_received(sender, message)
signal ui_phone_message_sent(receiver, message)
signal meth_lab_started
signal meth_lab_completed(quality, profit)
signal meth_lab_failed(reason)
signal meth_lab_progress_updated(progress)
signal meth_lab_chemical_added(chemical, amount)
signal meth_lab_temperature_changed(temperature)
signal meth_lab_reaction_state_changed(state)
signal meth_lab_batch_quality_updated(quality)
signal meth_lab_explosion(severity)
signal door_opened(door)
signal door_closed(door)
signal car_started(car)
signal car_stopped(car)
signal object_picked_up(object)
signal object_dropped(object)
signal object_broken(object)
signal object_used(object)
signal container_opened(container)
signal container_closed(container)
signal container_item_taken(container, item)
signal container_item_stored(container, item)
signal light_switched_on(light)
signal light_switched_off(light)
signal explosion_occurred(position, radius, damage)
signal fire_started(position)
signal fire_extinguished(position)
signal gun_fired(gun, position, direction)
signal bullet_hit(bullet, target, position)
signal character_damaged(character, damage, source)
signal character_healed(character, amount)
signal character_status_effect_applied(character, effect, duration)
signal character_status_effect_removed(character, effect)
signal cinematic_started(cinematic_name)
signal cinematic_ended(cinematic_name)
signal cinematic_skipped(cinematic_name)
signal camera_shake_requested(intensity, duration)
signal slow_motion_started(scale, duration)
signal slow_motion_ended
signal music_track_changed(track_name)
signal music_volume_changed(volume)
signal sound_played(sound_name, position)
signal ambient_sound_changed(ambient_name)
signal voice_line_started(character, line)
signal voice_line_ended(character)
signal debug_message(message)
signal debug_error(error)
signal debug_warning(warning)
signal debug_stat_changed(stat_name, value)
signal debug_console_command(command, args)
signal debug_console_output(output)
signal debug_fps_changed(fps)
signal debug_memory_usage_changed(usage)
signal car_wash_started
signal car_wash_car_cleaned(completion_percentage)
signal car_wash_completed
signal car_wash_money_earned(amount)
signal heat_level_increased(reason)
signal heat_level_decreased(reason)
signal heat_cooldown_started
signal heat_cooldown_ended